---
version: '3.9'
services:
  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /library.openapi.yaml'
    volumes:
      - ./api_spec/library.openapi.yaml:/library.openapi.yaml:ro
    ports:
      - '8080:4010'
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8081:8080"
    volumes:
      - ./api_spec/library.openapi.yaml:/library.openapi.yaml
    environment:
      SWAGGER_FILE: /library.openapi.yaml
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    volumes:
      - ./api_spec/library.openapi.yaml:/library.openapi.yaml:ro
    environment:
      SWAGGER_JSON: /library.openapi.yaml