openapi: 3.0.3
info:
  title: Library system
  version: 1.0.0
paths:
  /rented-books:
    get:
      summary: Get all rented books
      operationId: getRentedBooks
      responses:
        200:
          $ref: '#/components/responses/rentedBooksFetched'
  /rented-books/{rentedBookId}:
    delete:
      summary: Return a book
      operationId: returnABook
      parameters:
        - $ref: '#/components/parameters/rentedBookId'
      responses:
        200:
          description: book returned
  /books:
    get:
      summary: Get all books in the library
      operationId: getBooks
      responses:
        200:
          $ref: '#/components/responses/booksFetched'
  /books/{bookId}:
    get:
      summary: Get book identified by `bookId`
      operationId: getBookById
      parameters:
        - $ref: '#/components/parameters/bookId'
      responses:
        200:
          $ref: '#/components/responses/bookFetched'
  /books/{bookId}/rent:
    post:
      summary: Rent a book
      operationId: rentBook
      parameters:
        - $ref: '#/components/parameters/bookId'
      responses:
        200:
          $ref: '#/components/responses/rentedBookFetched'
components:
  schemas:
    book:
      type: object
      description: book object
      properties:
        id:
          type: string
          format: uuid
          description: Unique book identifier
          example: 5d9ff9d5-f71b-4608-bbfd-7cca54a77176
        title:
          type: string
          description: Book title
          example: Fantastic Mr. Fox
    rentedBook:
      type: object
      description: rented book object
      properties:
        id:
          type: string
          format: uuid
          description: Unique rented book identifier
          example: 5ceea7e8-b1f2-4a2b-afab-9d9f9a548e68
        bookId:
          type: string
          format: uuid
          description: Book identifier
          example: 9fff27cb-3d50-4b10-bea1-b2f33b3e7c14
        dueDate:
          type: string
          format: date
          description: Rental due date
          example: 2023-12-15
  responses:
    bookFetched:
      description: book fetched
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/book'
          example:
            id: c2085e12-9241-4b4e-87c5-453f52ae4e01
            title: Matilda
    booksFetched:
      description: books fetched
      content:
        application/json:
          schema:
            type: object
            properties:
              items: 
                type: array
                items: 
                  $ref: '#/components/schemas/book'
                example:
                  - id: 3b05f3e8-2702-430d-b97d-78ec4dcccaa8
                    title: The Cat in the Hat
                  - id: fe8b8f9f-ef09-406b-822f-f92eebf4bfe3
                    title: Matilda
    rentedBookFetched:
      description: rented book fetched
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/rentedBook"
    rentedBooksFetched:
      description: rented books fetched
      content:
        application/json:
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '#/components/schemas/rentedBook'
  parameters:
    bookId:
      name: bookId
      description: unique Id of a book in library
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: a9df16dc-a94a-43ee-b58f-3cb0e60286fc
    rentedBookId:
      name: rentedBookId
      description: unique Id of rented book
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: 164ece42-7f9b-49b0-b30f-f14b92d07473
